#!/usr/bin/env python3
"""
Function Map Categorizer - Universal config-driven categorization engine.

Reads _functions.json and _taxonomy.json to create hierarchical categorized
markdown files. Routes functions to semantic domain categories based on routing
rules defined in the project-specific taxonomy configuration.

All routing logic is data-driven from _taxonomy.json. No hard-coded project
knowledge. The taxonomy is designed by Claude during the function map workflow,
tailored to each project's unique structure and domain.

Routing rule priority (evaluated in order, first match wins):
  1. Third-party exclusion (patterns from taxonomy)
  2. Deprecated/legacy detection (patterns from taxonomy)
  3. Namespace routing (prefix matching from taxonomy)
  4. Directory routing (path prefix matching from taxonomy)
  5. File routing (exact file matching from taxonomy)
  6. Keyword routing (function name matching from taxonomy)
  7. Uncategorized fallback

Produces:
  - Category .md files with rich descriptions
  - Hierarchical index with category descriptions
  - Optional third-party-bundled.md reference

Usage:
    python categorize.py                          # Process latest project
    python categorize.py --project my-project      # Process specific project
"""

import json
import re
import sys
from pathlib import Path
from collections import defaultdict
from typing import Dict, List, Optional, Tuple


# Import rich description engine (optional - falls back to simple inference)
try:
    from describe import describe_function as _rich_describe
except ImportError:
    _rich_describe = None

# Import third-party library mapping (optional - graceful fallback)
try:
    from thirdparty import (
        group_by_library,
        map_library,
        update_index as tp_update_index,
        enhance_third_party_summary,
        generate_third_party_table,
        get_project_libs,
    )
    _has_thirdparty = True
except ImportError:
    _has_thirdparty = False


# =============================================================================
# Taxonomy loading
# =============================================================================

def load_taxonomy(project_dir: Path) -> dict:
    """Load the taxonomy config for a project.

    The _taxonomy.json file is generated by Claude during the function map
    workflow. It contains project-specific categories and routing rules.

    If no taxonomy exists, returns a minimal fallback that routes everything
    to 'uncategorized'.
    """
    taxonomy_path = project_dir / "_taxonomy.json"
    if not taxonomy_path.exists():
        print(f"[categorize] WARNING: No _taxonomy.json found in {project_dir}")
        print(f"[categorize] All functions will be uncategorized.")
        print(f"[categorize] Run the taxonomy design phase first to create proper categories.")
        return _minimal_taxonomy()

    with open(taxonomy_path, "r", encoding="utf-8") as f:
        taxonomy = json.load(f)

    # Validate basic structure
    if "categories" not in taxonomy:
        print(f"[categorize] WARNING: _taxonomy.json missing 'categories' key")
        taxonomy["categories"] = {}
    if "routing_rules" not in taxonomy:
        print(f"[categorize] WARNING: _taxonomy.json missing 'routing_rules' key")
        taxonomy["routing_rules"] = {}

    return taxonomy


# =============================================================================
# Enrichment loading (optional sidecar data)
# =============================================================================

def load_enrichment(project_dir: Path) -> dict:
    """Load optional _enrichment.json sidecar file for supplementary metadata.

    Enrichment files provide display names, descriptions, category hints, and
    other metadata that wasn't extractable from source code analysis. Any
    project can provide one -- it's fully optional.

    Returns the parsed enrichment dict, or {} if missing/invalid.
    """
    enrichment_path = project_dir / "_enrichment.json"
    if not enrichment_path.exists():
        return {}

    try:
        with open(enrichment_path, "r", encoding="utf-8") as f:
            enrichment = json.load(f)
    except (json.JSONDecodeError, ValueError) as e:
        print(f"[categorize] WARNING: _enrichment.json invalid JSON: {e}")
        return {}

    if enrichment.get("version") != 1:
        print(f"[categorize] WARNING: _enrichment.json unsupported version "
              f"(expected 1, got {enrichment.get('version')})")
        return {}

    if not isinstance(enrichment.get("entries"), dict):
        print(f"[categorize] WARNING: _enrichment.json missing or invalid 'entries' field")
        return {}

    return enrichment


def build_enrichment_index(enrichment: dict, functions: list) -> dict:
    """Build O(1) lookup from function ID to enrichment entry.

    Supports three key_format modes:
      - file:name:line  -- composite key (most precise, for normal projects)
      - name_only       -- keyed by short_name (for decompiled code with unique names)
      - custom          -- keyed by arbitrary match_field/match_value per entry

    Returns dict keyed by "file::short_name::line_start" -> enrichment entry.
    """
    if not enrichment or not enrichment.get("entries"):
        return {}

    entries    = enrichment["entries"]
    key_format = enrichment.get("key_format", "file:name:line")
    index      = {}

    if key_format == "name_only":
        # Build reverse lookup: short_name -> enrichment entry
        for fn in functions:
            name = fn.get("short_name", "")
            if name in entries:
                fn_key = f"{fn['file']}::{fn['short_name']}::{fn['line_start']}"
                index[fn_key] = entries[name]

    elif key_format == "custom":
        # Each entry specifies its own match_field and match_value
        for entry_key, entry_data in entries.items():
            match_field = entry_data.get("match_field", "short_name")
            match_value = entry_data.get("match_value", entry_key)
            for fn in functions:
                if fn.get(match_field) == match_value:
                    fn_key = f"{fn['file']}::{fn['short_name']}::{fn['line_start']}"
                    index[fn_key] = entry_data

    else:  # file:name:line (default)
        for fn in functions:
            fn_key = f"{fn['file']}::{fn['short_name']}::{fn['line_start']}"
            if fn_key in entries:
                index[fn_key] = entries[fn_key]

    return index


def _minimal_taxonomy() -> dict:
    """Return a minimal taxonomy for when no config exists."""
    return {
        "project": "unknown",
        "categories": {
            "uncategorized": {
                "description": "Functions that have not been categorized. "
                               "Run the taxonomy design phase to create proper categories.",
                "subcategories": {}
            }
        },
        "routing_rules": {}
    }


# =============================================================================
# Rule matching engine
# =============================================================================

def _matches_pattern(fp: str, fn: dict, rule: dict) -> bool:
    """Check if a function matches a pattern-based rule.

    Supported rule types:
      - path_contains:  case-insensitive substring match on file path
      - path_prefix:    file path starts with pattern
      - path_regex:     regex match against file path
      - file_exact:     exact file path match

    Optional modifiers:
      - exclude_language: skip match if function is in this language
    """
    rule_type = rule.get("type", "path_contains")
    pattern = rule.get("pattern", "")

    matched = False

    if rule_type == "path_contains":
        matched = pattern.lower() in fp.lower()

    elif rule_type == "path_prefix":
        matched = fp.startswith(pattern)

    elif rule_type == "path_regex":
        matched = bool(re.search(pattern, fp))

    elif rule_type == "file_exact":
        matched = fp == pattern

    if not matched:
        return False

    # Check optional language exclusion
    exclude_lang = rule.get("exclude_language")
    if exclude_lang and fn.get("language") == exclude_lang:
        return False

    return True


# =============================================================================
# Categorization engine
# =============================================================================

def is_third_party(fn: dict, taxonomy: dict) -> bool:
    """Check if a function belongs to excluded third-party code.

    Uses third_party patterns from the taxonomy routing rules.
    """
    fp = fn["file"].replace("\\", "/")
    rules = taxonomy.get("routing_rules", {})

    for rule in rules.get("third_party", []):
        if _matches_pattern(fp, fn, rule):
            return True
    return False


def categorize_function(
    fn: dict, taxonomy: dict, enrichment_entry: Optional[dict] = None
) -> Tuple[str, str]:
    """
    Categorize a function using routing rules from taxonomy config.

    Returns (top_category, subcategory) tuple.

    Rules are evaluated in priority order -- first match wins:
      1. Third-party exclusion (handled separately via is_third_party)
      2. Deprecated/legacy patterns
      3. Namespace routes (prefix matching)
      4. Directory routes (path prefix matching)
      5. File routes (exact file matching)
      6. Keyword routes (function name matching)
      6.5. Fallback file routing
      6.7. Enrichment category_hint (for otherwise-uncategorized functions)
      7. Uncategorized fallback
    """
    fp = fn["file"].replace("\\", "/")
    ns = fn.get("namespace") or ""
    cls = fn.get("class_name") or ""
    name = fn.get("short_name") or ""

    rules = taxonomy.get("routing_rules", {})

    # --- Rule 2: Deprecated/legacy detection ---
    for rule in rules.get("deprecated", []):
        if _matches_pattern(fp, fn, rule):
            cat = rule.get("category", "deprecated")
            sub = rule.get("subcategory", "other")
            return (cat, sub)

    # --- Rule 3: Namespace routing ---
    # Routes are evaluated in order -- more specific rules should come first
    for route in rules.get("namespace_routes", []):
        pattern = route.get("pattern", "")
        if not ns or not ns.startswith(pattern):
            continue

        # Optional class filter for sub-routing within a namespace
        class_filter = route.get("class")
        if class_filter and cls != class_filter:
            continue

        # Optional file_contains filter for sub-routing within a namespace
        file_filter = route.get("file_contains")
        if file_filter and file_filter.lower() not in fp.lower():
            continue

        cat = route["category"]
        sub = route.get("subcategory", "core")
        return (cat, sub)

    # --- Rule 4: Directory routing ---
    for route in rules.get("directory_routes", []):
        pattern = route.get("pattern", "")
        if fp.startswith(pattern):
            cat = route["category"]
            sub = route.get("subcategory", "core")
            return (cat, sub)

    # --- Rule 5: File routing ---
    for route in rules.get("file_routes", []):
        file_pattern = route.get("file", "")
        if fp == file_pattern:
            cat = route["category"]
            sub = route.get("subcategory", "core")
            return (cat, sub)

    # --- Rule 5.5: File map (dict lookup, O(1)) ---
    file_map = rules.get("file_map", {})
    if fp in file_map:
        entry = file_map[fp]
        cat = entry["category"]
        sub = entry.get("subcategory", "core")
        return (cat, sub)

    # --- Rule 6: Keyword routing ---
    name_lower = name.lower()
    for route in rules.get("keyword_routes", []):
        keywords = route.get("keywords", [])
        if any(kw.lower() in name_lower for kw in keywords):
            cat = route["category"]
            sub = route.get("subcategory", "core")
            return (cat, sub)

    # --- Rule 6.5: Fallback file routing (catch-all for multi-category files) ---
    for route in rules.get("fallback_file_routes", []):
        file_pattern = route.get("file", "")
        if fp == file_pattern:
            cat = route["category"]
            sub = route.get("subcategory", "core")
            return (cat, sub)

    # --- Rule 6.7: Enrichment category_hint (for otherwise-uncategorized functions) ---
    if enrichment_entry:
        hint = enrichment_entry.get("category_hint")
        if hint and hint in taxonomy.get("categories", {}):
            return (hint, "enriched")

    # --- Rule 7: Uncategorized fallback ---
    return ("uncategorized", "other")


# =============================================================================
# Category descriptions from taxonomy
# =============================================================================

def get_category_description(cat_key: str, taxonomy: dict) -> str:
    """Get description for a category from taxonomy config.

    Supports both "top-category" and "top-category/subcategory" key formats.
    Falls back to a generated description if no taxonomy entry exists.

    Subcategory values in the taxonomy can be either:
      - A string: the description directly
      - A dict with a "description" key
    """
    categories = taxonomy.get("categories", {})

    # Try "top/sub" format
    if "/" in cat_key:
        top, sub = cat_key.split("/", 1)
        top_cat = categories.get(top, {})
        subcats = top_cat.get("subcategories", {})
        if sub in subcats:
            sub_entry = subcats[sub]
            if isinstance(sub_entry, dict):
                return sub_entry.get("description", "")
            return str(sub_entry)
        # Fall back to top-level description
        if "description" in top_cat:
            return top_cat["description"]

    # Try top-level match
    if cat_key in categories:
        cat_entry = categories[cat_key]
        if isinstance(cat_entry, dict):
            return cat_entry.get("description", "")
        return str(cat_entry)

    # Generate fallback
    readable = cat_key.replace("-", " ").replace("_", " ")
    return f"Functions related to {readable}."


# =============================================================================
# Function description (simple fallback if describe.py is unavailable)
# =============================================================================

def extract_function_description(fn: dict) -> str:
    """Extract or infer a description for a function.

    Uses describe.py's rich engine if available, otherwise falls back
    to simple name-based inference.

    Priority:
    1. Rich description engine (describe.py)
    2. Docblock summary (if available)
    3. Inferred from function name
    """
    # Try rich description engine first
    if _rich_describe is not None:
        try:
            return _rich_describe(fn)
        except Exception:
            pass

    # Fallback: use existing summary from docblock
    if fn.get("summary"):
        summary = fn["summary"].strip()
        if not summary.startswith("@"):
            return summary

    # Fallback: infer from function name
    name = fn["short_name"]
    return_type = fn.get("return_type", "")

    readable = _name_to_readable(name)
    parts = [readable]

    if return_type and return_type not in ("unknown", "void", "mixed"):
        parts.append(f"Returns {return_type}.")

    return ". ".join(parts)


def _name_to_readable(name: str) -> str:
    """Convert function name to readable description."""
    clean_name = name.lstrip("_")
    if not clean_name:
        clean_name = name

    # Handle PHP magic methods
    if clean_name.startswith("__") or name.startswith("__"):
        magic = name.replace("__", "")
        if magic:
            return f"Magic method: {magic}"
        return name

    name = clean_name

    prefixes = {
        "get": "Gets", "set": "Sets", "is": "Checks if",
        "has": "Checks whether it has", "can": "Checks if it can",
        "should": "Determines if it should", "create": "Creates",
        "make": "Creates", "build": "Builds", "add": "Adds",
        "remove": "Removes", "delete": "Deletes", "update": "Updates",
        "save": "Saves", "load": "Loads", "find": "Finds",
        "search": "Searches for", "show": "Displays", "hide": "Hides",
        "render": "Renders", "display": "Displays", "format": "Formats",
        "parse": "Parses", "validate": "Validates", "check": "Checks",
        "init": "Initializes", "setup": "Sets up", "reset": "Resets",
        "clear": "Clears", "enable": "Enables", "disable": "Disables",
        "register": "Registers", "handle": "Handles", "process": "Processes",
        "convert": "Converts", "apply": "Applies", "execute": "Executes",
        "run": "Runs", "start": "Starts", "stop": "Stops",
        "send": "Sends", "fetch": "Fetches", "upload": "Uploads",
        "download": "Downloads", "import": "Imports", "export": "Exports",
        "encode": "Encodes", "decode": "Decodes", "log": "Logs",
        "filter": "Filters", "sort": "Sorts", "merge": "Merges",
        "count": "Counts", "normalize": "Normalizes", "sanitize": "Sanitizes",
        "escape": "Escapes", "clean": "Cleans", "open": "Opens",
        "close": "Closes", "connect": "Connects", "on": "Handler for",
    }

    if "_" in name:
        parts = name.split("_")
    else:
        parts = re.findall(r"[A-Z]?[a-z]+|[A-Z]+(?=[A-Z][a-z]|\d|\b)", name)
        if not parts:
            parts = [name]

    if not parts:
        return name

    first = parts[0].lower()
    rest = " ".join(p.lower() for p in parts[1:]) if len(parts) > 1 else ""

    if first in prefixes:
        verb = prefixes[first]
        if rest:
            return f"{verb} {rest}"
        return verb
    else:
        all_parts = " ".join(p.lower() for p in parts)
        return all_parts.capitalize()


# =============================================================================
# Purpose-based category splitting (universal)
# =============================================================================

MAX_CATEGORY_SIZE = 250


def split_large_categories(
    categories: Dict[str, Dict[str, List[dict]]]
) -> Dict[str, Dict[str, List[dict]]]:
    """
    Split subcategories exceeding MAX_CATEGORY_SIZE by purpose.

    Uses file path clustering to group related functions, NOT alphabetical
    splitting. Functions from the same source file stay together.
    """
    result = {}

    for top_cat, subcats in categories.items():
        result[top_cat] = {}

        for sub_name, funcs in subcats.items():
            if len(funcs) <= MAX_CATEGORY_SIZE:
                result[top_cat][sub_name] = funcs
                continue

            # Group by source file
            by_file: Dict[str, List[dict]] = defaultdict(list)
            for f in funcs:
                by_file[f["file"].replace("\\", "/")].append(f)

            sorted_files = sorted(by_file.keys())

            chunks: List[Tuple[str, List[dict]]] = []
            current_chunk: List[dict] = []
            current_label_parts: List[str] = []

            for filepath in sorted_files:
                file_funcs = by_file[filepath]

                if len(current_chunk) + len(file_funcs) > MAX_CATEGORY_SIZE and current_chunk:
                    chunk_label = _derive_chunk_label(current_label_parts)
                    chunks.append((chunk_label, current_chunk))
                    current_chunk = []
                    current_label_parts = []

                current_chunk.extend(file_funcs)
                current_label_parts.append(filepath)

            if current_chunk:
                chunk_label = _derive_chunk_label(current_label_parts)
                chunks.append((chunk_label, current_chunk))

            if len(chunks) == 1:
                result[top_cat][sub_name] = funcs
            else:
                for idx, (label, chunk_funcs) in enumerate(chunks, 1):
                    new_name = f"{sub_name}-{label}" if label else f"{sub_name}-part-{idx}"
                    if new_name in result[top_cat]:
                        new_name = f"{sub_name}-part-{idx}"
                    result[top_cat][new_name] = chunk_funcs

    return result


def _derive_chunk_label(file_paths: List[str]) -> str:
    """Derive a meaningful label from a list of file paths."""
    if not file_paths:
        return ""

    basenames = [p.split("/")[-1].replace(".php", "").replace(".js", "").replace(".ts", "") for p in file_paths]

    # If all from same directory, use directory name
    dirs = set(("/".join(p.split("/")[:-1]) for p in file_paths))
    if len(dirs) == 1:
        dir_name = list(dirs)[0].split("/")[-1] if list(dirs)[0] else ""
        if dir_name and dir_name not in ("lib", "src", "plugins", "vendor"):
            return dir_name.lower().replace(" ", "-")

    # Use first letter range
    if len(basenames) >= 2:
        first_letter = basenames[0][0].upper()
        last_letter = basenames[-1][0].upper()
        if first_letter != last_letter:
            return f"{first_letter}-{last_letter}"
        return f"{first_letter}"

    return basenames[0][:20].lower() if basenames else ""


# =============================================================================
# Markdown generation (universal)
# =============================================================================

def _get_usage_examples(top_cat: str, taxonomy: dict) -> list:
    """Get usage examples for a category from taxonomy config."""
    categories = taxonomy.get("categories", {})
    cat_entry = categories.get(top_cat, {})
    if isinstance(cat_entry, dict):
        return cat_entry.get("usage_examples", [])
    return []


def _format_subcategory_title(sub_name: str) -> str:
    """Format subcategory name into a human-readable title.

    Handles letter-range splits like 'admin-crud-A-F' -> 'Admin Crud (A-F)'
    and part splits like 'core-part-2' -> 'Core (Part 2)'.
    """
    range_match = re.match(r'^(.+?)-([A-Z_])-([A-Z])$', sub_name)
    if range_match:
        base = range_match.group(1).replace("-", " ").replace("_", " ").title()
        return f"{base} ({range_match.group(2)}-{range_match.group(3)})"

    letter_match = re.match(r'^(.+?)-([A-Z])$', sub_name)
    if letter_match:
        base = letter_match.group(1).replace("-", " ").replace("_", " ").title()
        return f"{base} ({letter_match.group(2)})"

    part_match = re.match(r'^(.+?)-part-(\d+)$', sub_name)
    if part_match:
        base = part_match.group(1).replace("-", " ").replace("_", " ").title()
        return f"{base} (Part {part_match.group(2)})"

    return sub_name.replace("-", " ").replace("_", " ").title()


def generate_category_markdown(
    top_cat: str, sub_name: str, funcs: List[dict], taxonomy: dict,
    enrichment_index: Optional[dict] = None,
) -> str:
    """Generate markdown content for a category file."""
    cat_key = f"{top_cat}/{sub_name}"
    title = _format_subcategory_title(sub_name)
    top_title = top_cat.replace("-", " ").replace("_", " ").title()
    description = get_category_description(cat_key, taxonomy)

    # Fall back to top-level description if subcategory has generic fallback
    fallback_check = get_category_description("__nonexistent__", taxonomy)
    if description == fallback_check:
        description = get_category_description(top_cat, taxonomy)

    lines = [
        f"# {top_title} > {title}",
        "",
        description,
        "",
    ]

    # Check for variant note (used by typed-variants categories)
    cat_entry = taxonomy.get("categories", {}).get(top_cat, {})
    variant_note = cat_entry.get("variant_note", "") if isinstance(cat_entry, dict) else ""
    if variant_note:
        lines.append(f"> **Note:** {variant_note}")
        lines.append("")

    lines.extend([
        f"**Function count:** {len(funcs)}",
        "",
        "---",
        "",
    ])

    # Usage examples from taxonomy
    examples = _get_usage_examples(top_cat, taxonomy)
    if examples:
        lines.append("## Common Patterns")
        lines.append("")
        for ex in examples:
            if ex.get("title"):
                lines.append(f"### {ex['title']}")
                lines.append("")
            lang = ex.get("language", "php")
            lines.append(f"```{lang}")
            lines.append(ex.get("code", ""))
            lines.append("```")
            lines.append("")
            if ex.get("notes"):
                lines.append(ex["notes"])
                lines.append("")
        lines.append("---")
        lines.append("")

    # Sort functions by name
    funcs.sort(key=lambda f: f["short_name"].lower())

    for func in funcs:
        # Look up enrichment data for this function
        fn_key = f"{func['file']}::{func['short_name']}::{func['line_start']}"
        enrich = enrichment_index.get(fn_key, {}) if enrichment_index else {}

        vis = f"{func['visibility']} " if func.get("visibility") else ""
        static = "static " if func.get("is_static") else ""
        async_m = "async " if func.get("is_async") else ""

        sig = f"{vis}{static}{async_m}{func['short_name']}({func['params']})"
        if func.get("return_type") and func["return_type"] != "unknown":
            sig += f": {func['return_type']}"

        # Heading: use displayName if enrichment provides one
        if enrich.get("displayName"):
            lines.append(f"## {enrich['displayName']} ({func['short_name']})")
        else:
            lines.append(f"## {func['short_name']}")
        lines.append("")

        # Description: prefer docblock, fall back to enrichment
        desc = extract_function_description(func)
        if not desc and enrich.get("description"):
            desc = enrich["description"]
        if desc:
            lines.append(desc)
            lines.append("")

        lines.append(f"**Signature:** `{sig}`")
        lines.append("")

        # Note about variant-preserving return types
        rtype = func.get("return_type", "")
        if rtype in ("static", "self", "$this"):
            lines.append("*Returns the same variant type as the caller (preserves subclass type).*")
            lines.append("")

        loc = f"{func['file']}:{func['line_start']}"
        if func["line_end"] != func["line_start"]:
            loc += f"-{func['line_end']}"
        lines.append(f"**Location:** `{loc}`")
        lines.append("")

        if func.get("namespace"):
            lines.append(f"**Namespace:** `{func['namespace']}`")
            lines.append("")
        if func.get("class_name"):
            lines.append(f"**Class:** `{func['class_name']}`")
            lines.append("")

        if func.get("attributes"):
            attrs = ", ".join(func["attributes"])
            lines.append(f"**Attributes:** `{attrs}`")
            lines.append("")

        # Enrichment metadata
        if enrich.get("library"):
            lines.append(f"**Library:** {enrich['library']}")
            lines.append("")

        if enrich.get("confidence") and enrich["confidence"] != "confident":
            lines.append(f"**Confidence:** {enrich['confidence']}")
            lines.append("")

        if enrich.get("tags"):
            tag_str = ", ".join(f"`{t}`" for t in enrich["tags"])
            lines.append(f"**Tags:** {tag_str}")
            lines.append("")

        if enrich.get("notes"):
            lines.append(f"*{enrich['notes']}*")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def generate_index(
    categories: Dict[str, Dict[str, List[dict]]],
    project_name: str,
    third_party_count: int,
    taxonomy: dict,
    enrichment: Optional[dict] = None,
) -> str:
    """Generate hierarchical project index markdown."""
    total_funcs = sum(
        len(funcs)
        for subcats in categories.values()
        for funcs in subcats.values()
    )
    total_subcats = sum(len(subcats) for subcats in categories.values())

    lines = [
        f"# {project_name} Function Map",
        "",
        f"**Total functions:** {total_funcs}",
    ]
    if third_party_count > 0:
        lines[-1] += f" (excludes {third_party_count} bundled third-party functions)"
    lines.append(f"**Categories:** {len(categories)} top-level, {total_subcats} subcategories")
    if enrichment and enrichment.get("entries"):
        entry_count = len(enrichment["entries"])
        source = enrichment.get("source", "unknown")
        lines.append(f"**Enrichment:** {entry_count} entries from {source}")
    lines.extend([
        "",
        "---",
        "",
    ])

    # Order categories: use taxonomy ordering if available, then alphabetical
    taxonomy_cats = list(taxonomy.get("categories", {}).keys())
    all_cats = set(categories.keys())

    # Taxonomy order first, then any extras alphabetically
    ordered_cats = [c for c in taxonomy_cats if c in all_cats]
    ordered_cats.extend(sorted(all_cats - set(ordered_cats)))

    for top_cat in ordered_cats:
        if top_cat not in categories:
            continue
        subcats = categories[top_cat]
        top_title = top_cat.replace("-", " ").replace("_", " ").title()
        top_desc = get_category_description(top_cat, taxonomy)
        top_count = sum(len(funcs) for funcs in subcats.values())

        lines.append(f"## {top_title}")
        lines.append("")
        lines.append(f"*{top_desc}*")
        lines.append("")
        sub_word = "subcategory" if len(subcats) == 1 else "subcategories"
        lines.append(f"**{top_count} functions** across {len(subcats)} {sub_word}:")
        lines.append("")

        for sub_name in sorted(subcats.keys()):
            funcs = subcats[sub_name]
            sub_title = _format_subcategory_title(sub_name)
            filename = f"{top_cat}--{sub_name}.md"
            sub_key = f"{top_cat}/{sub_name}"
            sub_desc = get_category_description(sub_key, taxonomy)

            if len(sub_desc) > 120:
                sub_desc = sub_desc[:117] + "..."

            lines.append(f"- **[{sub_title}]({filename})** ({len(funcs)}) -- {sub_desc}")

        lines.append("")

    lines.extend([
        "## Usage",
        "",
        "1. Browse categories above to find relevant functions",
        "2. Click subcategory link to see function signatures, descriptions, and locations",
        "3. Use location info to read source code for implementation details",
        "",
    ])

    return "\n".join(lines)


def generate_third_party_summary(
    third_party_funcs: List[dict], taxonomy: dict
) -> str:
    """Generate a summary file for excluded third-party code.

    Groups functions by which taxonomy rule excluded them, using the rule's
    'reason' field as the group label. Universal -- no hard-coded library names.
    """
    rules = taxonomy.get("routing_rules", {}).get("third_party", [])

    # Group functions by the matching rule's reason
    groups: Dict[str, List[dict]] = defaultdict(list)
    for fn in third_party_funcs:
        fp = fn["file"].replace("\\", "/")
        matched_reason = "Other"
        for rule in rules:
            if _matches_pattern(fp, fn, rule):
                matched_reason = rule.get("reason", rule.get("pattern", "Unknown"))
                break
        groups[matched_reason].append(fn)

    lines = [
        "# Third-Party Bundled Libraries",
        "",
        "These functions are from bundled third-party libraries and are excluded from the main function map.",
        "",
        f"**Total third-party functions:** {len(third_party_funcs)}",
        "",
        "---",
        "",
    ]

    for group_name, funcs in sorted(groups.items(), key=lambda x: -len(x[1])):
        files = sorted(set(fn["file"] for fn in funcs))
        lines.append(f"## {group_name} ({len(funcs)} functions)")
        lines.append("")
        lines.append(f"**Files:** {len(files)}")
        lines.append("")
        for f in files[:20]:
            lines.append(f"- `{f}`")
        if len(files) > 20:
            lines.append(f"- *...and {len(files) - 20} more files*")
        lines.append("")

    return "\n".join(lines)


# =============================================================================
# Main
# =============================================================================

def main():
    import argparse

    ap = argparse.ArgumentParser(
        prog="categorize",
        description="Universal config-driven function categorization engine."
    )
    ap.add_argument(
        "--project", default="",
        help="Project name (default: most recent in ~/.claude/functionmap)"
    )
    ap.add_argument(
        "--max-category-size", type=int, default=250,
        help="Max functions per subcategory file before auto-splitting (default: 250)"
    )
    args = ap.parse_args()

    global MAX_CATEGORY_SIZE
    MAX_CATEGORY_SIZE = args.max_category_size

    home = Path.home()
    base = home / ".claude" / "functionmap"

    # Find project
    if args.project:
        project_dir = base / args.project
    else:
        meta_files = list(base.glob("*/_meta.json"))
        if not meta_files:
            print("[categorize] No projects found")
            return
        meta_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        project_dir = meta_files[0].parent

    project_name = project_dir.name
    print(f"[categorize] Project: {project_name}")

    # Load taxonomy
    taxonomy = load_taxonomy(project_dir)
    print(f"[categorize] Taxonomy: {len(taxonomy.get('categories', {}))} categories, "
          f"{sum(len(r) for r in taxonomy.get('routing_rules', {}).values())} routing rules")

    # Load functions
    functions_json = project_dir / "_functions.json"
    if not functions_json.exists():
        print(f"[categorize] ERROR: {functions_json} not found")
        return

    with open(functions_json, "r", encoding="utf-8") as f:
        all_functions = json.load(f)

    print(f"[categorize] Total functions: {len(all_functions)}")

    # Load enrichment (optional sidecar data)
    enrichment = load_enrichment(project_dir)
    enrichment_index = {}
    if enrichment:
        enrichment_index = build_enrichment_index(enrichment, all_functions)
        matched = len(enrichment_index)
        total_entries = len(enrichment.get("entries", {}))
        source = enrichment.get("source", "unknown")
        print(f"[categorize] Enrichment: {total_entries} entries, "
              f"{matched} matched to functions (source: {source})")

    # Separate third-party from first-party (Rule 1)
    third_party = [fn for fn in all_functions if is_third_party(fn, taxonomy)]
    first_party = [fn for fn in all_functions if not is_third_party(fn, taxonomy)]
    print(f"[categorize] Third-party (excluded): {len(third_party)}")
    print(f"[categorize] First-party (categorizing): {len(first_party)}")

    # Map third-party libraries to shared location
    mapped_libs = {}
    if third_party and _has_thirdparty:
        print("[categorize] Mapping third-party libraries...")
        # Load source root from _meta.json for metadata
        meta_path = project_dir / "_meta.json"
        source_root = ""
        if meta_path.exists():
            try:
                meta = json.load(open(meta_path, encoding="utf-8"))
                source_root = meta.get("root_path", "")
            except (json.JSONDecodeError, ValueError):
                pass

        lib_groups = group_by_library(third_party, taxonomy, project_root=source_root)
        for key, group in lib_groups.items():
            if key == "_unresolved":
                unresolved_count = len(group.get("functions", []))
                if unresolved_count > 0:
                    print(f"[categorize] Third-party unresolved: {unresolved_count} functions "
                          f"(no library/version detected)")
                continue
            lib_name = group["library"]
            version = group["version"]
            result = map_library(
                lib_name, version, group["functions"],
                project_name, base, source_root=source_root,
            )
            if result:
                mapped_libs[key] = result
                tp_update_index(base, lib_name, version, result, project_name)

        if mapped_libs:
            print(f"[categorize] Mapped {len(mapped_libs)} third-party libraries")

    # Categorize using routing rules
    print("[categorize] Categorizing by routing rules...")
    raw_categories: Dict[str, Dict[str, List[dict]]] = defaultdict(lambda: defaultdict(list))

    for fn in first_party:
        fn_key = f"{fn['file']}::{fn['short_name']}::{fn['line_start']}"
        enrich_entry = enrichment_index.get(fn_key)
        top_cat, sub_cat = categorize_function(fn, taxonomy, enrichment_entry=enrich_entry)
        raw_categories[top_cat][sub_cat].append(fn)

    top_count = len(raw_categories)
    sub_count = sum(len(subs) for subs in raw_categories.values())
    print(f"[categorize] Raw: {top_count} top-level, {sub_count} subcategories")

    # Merge very small subcategories (< 3 functions) into parent "other"
    print("[categorize] Consolidating tiny subcategories...")
    categories: Dict[str, Dict[str, List[dict]]] = {}
    for top_cat, subcats in raw_categories.items():
        categories[top_cat] = {}
        for sub_name, funcs in subcats.items():
            if len(funcs) < 3 and sub_name not in ("core", "other"):
                categories[top_cat].setdefault("other", []).extend(funcs)
            else:
                categories[top_cat][sub_name] = funcs

    sub_count = sum(len(subs) for subs in categories.values())
    print(f"[categorize] After consolidation: {len(categories)} top-level, {sub_count} subcategories")

    # Split oversized categories by purpose
    print("[categorize] Splitting oversized categories by purpose...")
    categories = split_large_categories(categories)
    sub_count = sum(len(subs) for subs in categories.values())
    print(f"[categorize] Final: {len(categories)} top-level, {sub_count} subcategories")

    # Clean old category files (only category -- files and third-party-bundled.md)
    print("[categorize] Cleaning old category files...")
    for md_file in project_dir.glob("*.md"):
        if "--" in md_file.name or md_file.name == "third-party-bundled.md":
            md_file.unlink()

    # Generate category markdown files
    print("[categorize] Generating category files...")
    file_count = 0
    for top_cat, subcats in sorted(categories.items()):
        for sub_name, funcs in sorted(subcats.items()):
            md_content = generate_category_markdown(
                top_cat, sub_name, funcs, taxonomy,
                enrichment_index=enrichment_index,
            )
            filename = f"{top_cat}--{sub_name}.md"
            md_path = project_dir / filename
            md_path.write_text(md_content, encoding="utf-8")
            file_count += 1

    print(f"[categorize] Generated {file_count} category files")

    # Generate third-party summary
    if third_party:
        print("[categorize] Generating third-party summary...")
        tp_content = generate_third_party_summary(third_party, taxonomy)
        # Enhance with mapped library links
        if mapped_libs and _has_thirdparty:
            tp_content = enhance_third_party_summary(
                tp_content, mapped_libs, third_party, taxonomy
            )
        tp_path = project_dir / "third-party-bundled.md"
        tp_path.write_text(tp_content, encoding="utf-8")

    # Generate index
    print("[categorize] Generating index...")
    index_content = generate_index(
        categories, project_name, len(third_party), taxonomy,
        enrichment=enrichment,
    )

    # Append third-party library table if any were mapped
    if _has_thirdparty:
        tp_table = generate_third_party_table(base, project_name)
        if tp_table:
            index_content += "\n" + tp_table

    index_path = base / f"{project_name}.md"
    index_path.write_text(index_content, encoding="utf-8")
    print(f"[categorize] Index: {index_path}")

    # Print category summary
    print()
    print("[categorize] === CATEGORY SUMMARY ===")
    for top_cat in sorted(categories.keys()):
        subcats = categories[top_cat]
        total = sum(len(f) for f in subcats.values())
        sub_names = ", ".join(sorted(subcats.keys()))
        print(f"  {top_cat}: {total} functions ({len(subcats)} subcats: {sub_names})")

    # Print overall summary
    total_first_party = sum(
        len(funcs)
        for subcats in categories.values()
        for funcs in subcats.values()
    )
    print()
    print(f"[categorize] === SUMMARY ===")
    print(f"[categorize] Project: {project_name}")
    print(f"[categorize] First-party functions: {total_first_party}")
    print(f"[categorize] Third-party excluded: {len(third_party)}")
    print(f"[categorize] Top-level categories: {len(categories)}")
    print(f"[categorize] Total subcategories: {sub_count}")
    print(f"[categorize] Category files: {file_count}")
    if mapped_libs:
        print(f"[categorize] Third-party libs mapped: {len(mapped_libs)}")
        for key, info in sorted(mapped_libs.items()):
            status = info.get("status", "mapped")
            note = f" (needs docs)" if status == "needs_docs" else ""
            print(f"[categorize]   {key}: {info.get('function_count', 0)} functions{note}")
    if enrichment:
        enriched_routed = sum(
            1 for subcats in categories.values()
            for sub_name, funcs in subcats.items()
            if sub_name == "enriched" for _ in funcs
        )
        print(f"[categorize] Enrichment source: {enrichment.get('source', 'unknown')}")
        if enriched_routed:
            print(f"[categorize] Enrichment rescued from uncategorized: {enriched_routed}")
    print(f"[categorize] Index: ~/.claude/functionmap/{project_name}.md")


if __name__ == "__main__":
    main()
