#!/usr/bin/env python3
"""
describe.py -- Universal rich description generation for function map categories and functions.

Generates human-readable, actionable descriptions for:
1. Categories (from taxonomy config or generated from function analysis)
2. Individual functions (extracted from docblocks or inferred from signatures)

Description inference is fully universal -- uses function name analysis (170+ verb
templates), parameter analysis, return type analysis, and namespace/class context.
No project-specific knowledge is hard-coded.

Category descriptions come from the project's _taxonomy.json (generated by Claude
during the function map workflow). Falls back to function analysis when no taxonomy
is available.

Usage:
    python describe.py --stats            # Show description coverage statistics
    python describe.py --dry-run          # Preview descriptions without writing
    python describe.py --project my-project  # Target specific project
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# Fallback template for categories not explicitly listed
CATEGORY_DESCRIPTION_FALLBACK = (
    "Functions grouped by the '{name}' pattern. "
    "These share common functionality related to {readable_name}."
)


# =============================================================================
# FUNCTION DESCRIPTION INFERENCE ENGINE
# =============================================================================

# Verb patterns for function name analysis.
# Maps verb prefixes to description templates.
# {noun} is replaced with the inferred subject from the rest of the name.
VERB_TEMPLATES: Dict[str, str] = {
    'do':        "Performs {noun} operation.",
    'get':       "Retrieves {noun}.",
    'set':       "Sets or updates {noun}.",
    'is':        "Checks whether {noun}.",
    'has':       "Checks if {noun} exists or is present.",
    'can':       "Checks if {noun} is allowed or possible.",
    'should':    "Determines whether {noun} should occur.",
    'will':      "Determines whether {noun} will occur.",
    'was':       "Checks if {noun} has already occurred.",
    'did':       "Checks if {noun} was completed.",
    'add':       "Adds {noun}.",
    'remove':    "Removes {noun}.",
    'delete':    "Deletes {noun}.",
    'create':    "Creates a new {noun}.",
    'destroy':   "Destroys {noun} and releases resources.",
    'find':      "Searches for and returns {noun}.",
    'search':    "Searches for {noun} matching criteria.",
    'show':      "Displays {noun} in the UI.",
    'hide':      "Hides {noun} from the UI.",
    'render':    "Renders {noun} as HTML or visual output.",
    'display':   "Displays {noun} to the user.",
    'update':    "Updates existing {noun}.",
    'save':      "Saves {noun} to persistent storage.",
    'load':      "Loads {noun} from storage or external source.",
    'fetch':     "Fetches {noun} from a remote source.",
    'init':      "Initializes {noun}.",
    'initialize': "Initializes {noun}.",
    'setup':     "Sets up {noun} with required configuration.",
    'configure': "Configures {noun} settings.",
    'register':  "Registers {noun} with the system.",
    'unregister': "Unregisters {noun} from the system.",
    'enable':    "Enables {noun}.",
    'disable':   "Disables {noun}.",
    'activate':  "Activates {noun}.",
    'deactivate': "Deactivates {noun}.",
    'start':     "Starts {noun}.",
    'stop':      "Stops {noun}.",
    'open':      "Opens {noun}.",
    'close':     "Closes {noun}.",
    'begin':     "Begins {noun}.",
    'end':       "Ends {noun}.",
    'reset':     "Resets {noun} to default state.",
    'clear':     "Clears {noun}.",
    'clean':     "Cleans {noun}.",
    'build':     "Builds {noun} from components.",
    'compile':   "Compiles {noun}.",
    'parse':     "Parses {noun} from raw input.",
    'format':    "Formats {noun} for display.",
    'convert':   "Converts {noun} to a different format.",
    'transform': "Transforms {noun}.",
    'encode':    "Encodes {noun}.",
    'decode':    "Decodes {noun}.",
    'encrypt':   "Encrypts {noun}.",
    'decrypt':   "Decrypts {noun}.",
    'hash':      "Hashes {noun}.",
    'validate':  "Validates {noun}.",
    'verify':    "Verifies {noun}.",
    'check':     "Checks {noun}.",
    'test':      "Tests {noun}.",
    'assert':    "Asserts that {noun}.",
    'ensure':    "Ensures {noun}.",
    'require':   "Requires {noun}.",
    'send':      "Sends {noun}.",
    'receive':   "Receives {noun}.",
    'emit':      "Emits {noun} event.",
    'fire':      "Fires {noun} event.",
    'trigger':   "Triggers {noun}.",
    'dispatch':  "Dispatches {noun}.",
    'notify':    "Sends notification about {noun}.",
    'publish':   "Publishes {noun}.",
    'subscribe': "Subscribes to {noun} events.",
    'listen':    "Listens for {noun} events.",
    'handle':    "Handles {noun}.",
    'process':   "Processes {noun}.",
    'execute':   "Executes {noun}.",
    'run':       "Runs {noun}.",
    'apply':     "Applies {noun}.",
    'invoke':    "Invokes {noun}.",
    'call':      "Calls {noun}.",
    'insert':    "Inserts {noun}.",
    'append':    "Appends {noun}.",
    'prepend':   "Prepends {noun}.",
    'push':      "Pushes {noun} onto collection.",
    'pop':       "Removes and returns last {noun}.",
    'shift':     "Removes and returns first {noun}.",
    'unshift':   "Prepends {noun} to collection.",
    'sort':      "Sorts {noun}.",
    'filter':    "Filters {noun} by criteria.",
    'map':       "Maps over {noun}, transforming each item.",
    'reduce':    "Reduces {noun} to a single value.",
    'merge':     "Merges {noun} together.",
    'split':     "Splits {noun} into parts.",
    'join':      "Joins {noun} together.",
    'group':     "Groups {noun} by criteria.",
    'count':     "Counts {noun}.",
    'sum':       "Calculates sum of {noun}.",
    'select':    "Selects {noun}.",
    'deselect':  "Deselects {noun}.",
    'toggle':    "Toggles {noun} state.",
    'swap':      "Swaps {noun}.",
    'replace':   "Replaces {noun}.",
    'move':      "Moves {noun}.",
    'copy':      "Copies {noun}.",
    'clone':     "Clones {noun}.",
    'duplicate': "Duplicates {noun}.",
    'wrap':      "Wraps {noun} in a container.",
    'unwrap':    "Unwraps {noun} from its container.",
    'bind':      "Binds {noun}.",
    'unbind':    "Unbinds {noun}.",
    'attach':    "Attaches {noun}.",
    'detach':    "Detaches {noun}.",
    'mount':     "Mounts {noun}.",
    'unmount':   "Unmounts {noun}.",
    'connect':   "Connects {noun}.",
    'disconnect': "Disconnects {noun}.",
    'resize':    "Resizes {noun}.",
    'scroll':    "Scrolls {noun}.",
    'focus':     "Focuses {noun}.",
    'blur':      "Removes focus from {noun}.",
    'expand':    "Expands {noun}.",
    'collapse':  "Collapses {noun}.",
    'maximize':  "Maximizes {noun}.",
    'minimize':  "Minimizes {noun}.",
    'refresh':   "Refreshes {noun}.",
    'reload':    "Reloads {noun}.",
    'restore':   "Restores {noun}.",
    'revoke':    "Revokes {noun}.",
    'grant':     "Grants {noun}.",
    'deny':      "Denies {noun}.",
    'allow':     "Allows {noun}.",
    'block':     "Blocks {noun}.",
    'lock':      "Locks {noun}.",
    'unlock':    "Unlocks {noun}.",
    'freeze':    "Freezes {noun}.",
    'unfreeze':  "Unfreezes {noun}.",
    'cancel':    "Cancels {noun}.",
    'abort':     "Aborts {noun}.",
    'retry':     "Retries {noun}.",
    'skip':      "Skips {noun}.",
    'ignore':    "Ignores {noun}.",
    'accept':    "Accepts {noun}.",
    'reject':    "Rejects {noun}.",
    'approve':   "Approves {noun}.",
    'confirm':   "Confirms {noun}.",
    'submit':    "Submits {noun}.",
    'publish':   "Publishes {noun}.",
    'unpublish': "Unpublishes {noun}.",
    'archive':   "Archives {noun}.",
    'unarchive': "Unarchives {noun}.",
    'export':    "Exports {noun}.",
    'import':    "Imports {noun}.",
    'upload':    "Uploads {noun}.",
    'download':  "Downloads {noun}.",
    'print':     "Prints {noun}.",
    'log':       "Logs {noun}.",
    'debug':     "Outputs debug information for {noun}.",
    'dump':      "Dumps {noun} for inspection.",
    'trace':     "Traces {noun} execution.",
    'profile':   "Profiles {noun} performance.",
    'cache':     "Caches {noun}.",
    'invalidate': "Invalidates cached {noun}.",
    'flush':     "Flushes {noun}.",
    'sanitize':  "Sanitizes {noun} for safe use.",
    'escape':    "Escapes special characters in {noun}.",
    'unescape':  "Unescapes special characters in {noun}.",
    'strip':     "Strips {noun}.",
    'trim':      "Trims whitespace from {noun}.",
    'normalize': "Normalizes {noun} to standard form.",
    'calculate': "Calculates {noun}.",
    'compute':   "Computes {noun}.",
    'derive':    "Derives {noun} from existing data.",
    'extract':   "Extracts {noun} from source data.",
    'resolve':   "Resolves {noun}.",
    'lookup':    "Looks up {noun}.",
    'match':     "Matches {noun} against patterns.",
    'compare':   "Compares {noun}.",
    'diff':      "Computes difference in {noun}.",
    'patch':     "Patches {noun}.",
    'fix':       "Fixes {noun}.",
    'repair':    "Repairs {noun}.",
    'migrate':   "Migrates {noun}.",
    'upgrade':   "Upgrades {noun}.",
    'downgrade': "Downgrades {noun}.",
    'install':   "Installs {noun}.",
    'uninstall': "Uninstalls {noun}.",
}

# Return type hints for enriching descriptions
RETURN_TYPE_HINTS: Dict[str, str] = {
    'bool':     'Returns true/false.',
    'boolean':  'Returns true/false.',
    '{Boolean}': 'Returns true/false.',
    'int':      'Returns an integer value.',
    'float':    'Returns a numeric value.',
    'string':   'Returns a string value.',
    '{String}': 'Returns a string value.',
    'array':    'Returns an array.',
    '{Array}':  'Returns an array.',
    '{Object}': 'Returns an object.',
    'void':     '',  # No additional hint for void
    'never':    'This function always throws or exits.',
    'null':     'Returns null.',
    'self':     'Returns the current instance for method chaining.',
    'static':   'Returns the current instance for method chaining.',
    '$this':    'Returns the current instance for method chaining.',
}

# File path context hints - populated from taxonomy at runtime (no hard-coded paths)
FILE_PATH_CONTEXT: Dict[str, str] = {}


# Known compound words/acronyms that should not be split.
# Maps lowercase -> preferred display form.
COMPOUND_WORDS: Dict[str, str] = {
    'tinymce':     'TinyMCE',
    'mysql':       'MySQL',
    'mariadb':     'MariaDB',
    'oauth':       'OAuth',
    'oauth2':      'OAuth2',
    'iframe':      'iframe',
    'javascript':  'JavaScript',
    'textarea':    'textarea',
    'checkbox':    'checkbox',
    'dropdown':    'dropdown',
    'popup':       'popup',
    'tooltip':     'tooltip',
    'toolbar':     'toolbar',
    'sidebar':     'sidebar',
    'navbar':      'navbar',
    'menubar':     'menubar',
    'statusbar':   'statusbar',
    'scrollbar':   'scrollbar',
    'filepath':    'file path',
    'filename':    'file name',
    'username':    'username',
    'password':    'password',
    'timestamp':   'timestamp',
    'datetime':    'date/time',
    'timezone':    'timezone',
    'stylesheet':  'stylesheet',
    'wysiwyg':     'WYSIWYG',
    'cms':         'CMS',
    'html':        'HTML',
    'css':         'CSS',
    'url':         'URL',
    'uri':         'URI',
    'api':         'API',
    'ajax':        'AJAX',
    'json':        'JSON',
    'xml':         'XML',
    'csv':         'CSV',
    'sql':         'SQL',
    'smtp':        'SMTP',
    'http':        'HTTP',
    'https':       'HTTPS',
    'ssl':         'SSL',
    'tls':         'TLS',
    'php':         'PHP',
    'dom':         'DOM',
    'ui':          'UI',
    'xss':         'XSS',
    'csrf':        'CSRF',
    'pdf':         'PDF',
    'svg':         'SVG',
    'gif':         'GIF',
    'png':         'PNG',
    'jpg':         'JPG',
    'exif':        'EXIF',
    'utf8':        'UTF-8',
    'uuid':        'UUID',
    'cron':        'cron',
    'regex':       'regex',
    'regexp':      'regexp',
    'cdn':         'CDN',
    'ip':          'IP',
    'dns':         'DNS',
    'ftp':         'FTP',
    'ssh':         'SSH',
    'aws':         'AWS',
    's3':          'S3',
}

# Proper nouns that should always be capitalized
PROPER_NOUNS = {
    'google', 'amazon', 'aws', 'stripe', 'paypal', 'authorize',
    'mailchimp', 'sendgrid', 'twilio', 'facebook', 'twitter',
    'github', 'wordpress', 'drupal', 'joomla', 'magento',
    'jquery', 'tinymce', 'ckeditor', 'codemirror',
}


def _apply_compound_words(text: str) -> str:
    """Replace known compound words with their preferred display form."""
    result = text
    for compound, display in COMPOUND_WORDS.items():
        # Case-insensitive word boundary replacement
        pattern = re.compile(re.escape(compound), re.IGNORECASE)
        result = pattern.sub(display, result)
    return result


def _split_name_parts(name: str) -> List[str]:
    """Split a function name into semantic parts.

    Handles snake_case, camelCase, PascalCase, and mixed styles.
    Leading underscores (private convention) are stripped.
    Recognizes known compound words/acronyms.

    Examples:
        'getUserName'        -> ['get', 'User', 'Name']
        'is_valid_email'     -> ['is', 'valid', 'email']
        '_privateHelper'     -> ['private', 'Helper']
        'HTMLParser'         -> ['HTML', 'Parser']
        'isTinyMCELoaded'    -> ['is', 'TinyMCE', 'Loaded']
    """
    # Strip leading underscores
    clean = name.lstrip('_')
    if not clean:
        return [name]

    # If snake_case, split on underscores first, then split each part by camelCase
    if '_' in clean:
        result = []
        for segment in clean.split('_'):
            if not segment:
                continue
            # Check if segment contains camelCase (e.g., getMysqlSetValues)
            sub_parts = re.findall(
                r'[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+|[0-9]+', segment
            )
            result.extend(sub_parts if sub_parts else [segment])
        return result

    # camelCase/PascalCase split
    parts = re.findall(r'[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+|[0-9]+', clean)
    return parts if parts else [clean]


def _humanize_noun_parts(parts: List[str]) -> str:
    """Convert name parts into a readable noun phrase, recognizing compound words.

    Examples:
        ['Tiny', 'MCE', 'Loaded']   -> 'TinyMCE loaded'
        ['Google', 'Id', 'Token']   -> 'Google ID token'
        ['MySQL', 'Set', 'Values']  -> 'MySQL set values'
    """
    if not parts:
        return 'the value'

    # First merge adjacent parts that form known compound words
    merged = _merge_compound_parts(parts)

    # Then format each part
    processed = []
    for w in merged:
        lower = w.lower()
        if lower in COMPOUND_WORDS:
            processed.append(COMPOUND_WORDS[lower])
        elif lower in PROPER_NOUNS:
            # Keep proper nouns capitalized
            processed.append(w if w[0].isupper() else w.capitalize())
        elif w.isupper() and len(w) <= 5:
            processed.append(w)
        elif w[0].isupper() and len(w) > 1 and not w.isupper():
            processed.append(w[0].lower() + w[1:])
        else:
            processed.append(w.lower())

    return ' '.join(processed)


def _merge_compound_parts(parts: List[str]) -> List[str]:
    """Merge adjacent name parts that form known compound words.

    E.g., ['Tiny', 'MCE'] -> ['TinyMCE']
          ['My', 'SQL']   -> ['MySQL']
          ['Java', 'Script'] -> ['JavaScript']
    """
    if len(parts) <= 1:
        return list(parts)

    result = []
    i = 0
    while i < len(parts):
        merged = False
        # Try merging 3 parts, then 2
        for window in (3, 2):
            if i + window <= len(parts):
                candidate = ''.join(parts[i:i + window])
                if candidate.lower() in COMPOUND_WORDS:
                    result.append(candidate)
                    i += window
                    merged = True
                    break
        if not merged:
            result.append(parts[i])
            i += 1

    return result


def _extract_verb_and_noun(name: str) -> Tuple[str, str]:
    """Extract the verb prefix and noun subject from a function name.

    Returns (verb, noun_phrase) where noun_phrase is human-readable.

    Examples:
        'getUserEmail'     -> ('get', 'user email')
        'is_valid'         -> ('is', 'valid')
        'createNewRecord'  -> ('create', 'new record')
        'onClick'          -> ('on', 'click')
        'isTinyMCELoaded'  -> ('is', 'TinyMCE is loaded')
    """
    parts = _split_name_parts(name)
    if not parts:
        return ('', name)

    first = parts[0].lower()

    # Check if first part is a known verb
    if first in VERB_TEMPLATES:
        noun_parts = parts[1:]
        noun = _humanize_noun_parts(noun_parts)
        return (first, noun)

    # Check two-word verbs (e.g., 'setUp', 'tearDown')
    if len(parts) >= 2:
        two_word = (parts[0] + parts[1]).lower()
        if two_word in VERB_TEMPLATES:
            noun_parts = parts[2:]
            noun = _humanize_noun_parts(noun_parts)
            return (two_word, noun)

    return ('', name)


def _infer_from_params(params: str) -> str:
    """Infer additional context from parameter names and types.

    Examples:
        '$tableName, $where'     -> 'Operates on database table with conditions.'
        '$email, $password'      -> 'Operates on user credentials.'
        '$file, $uploadDir'      -> 'Operates on file uploads.'
    """
    if not params:
        return ''

    param_lower = params.lower()
    hints = []

    # Parameter name patterns -> context hints
    param_patterns = [
        (r'\$table|\$tablename', 'database table'),
        (r'\$record|\$row', 'database record'),
        (r'\$schema', 'table schema'),
        (r'\$field|\$fieldname|\$column', 'field/column'),
        (r'\$file|\$filepath|\$filename', 'file'),
        (r'\$image|\$img', 'image'),
        (r'\$email', 'email'),
        (r'\$password|\$pass', 'password'),
        (r'\$user|\$username|\$userid', 'user'),
        (r'\$url|\$uri|\$href', 'URL'),
        (r'\$html|\$markup', 'HTML content'),
        (r'\$css|\$style', 'CSS styles'),
        (r'\$query|\$sql', 'SQL query'),
        (r'\$request|\$req', 'HTTP request'),
        (r'\$response|\$res', 'HTTP response'),
        (r'\$plugin', 'plugin'),
        (r'\$hook|\$action|\$filter', 'hook/filter'),
        (r'\$template|\$tpl', 'template'),
        (r'\$cache', 'cache'),
        (r'\$config|\$settings|\$options', 'configuration'),
        (r'\$path|\$dir|\$directory', 'filesystem path'),
        (r'\$date|\$time|\$datetime', 'date/time'),
        (r'\$element|\$el|\$node', 'DOM element'),
        (r'\$event|\$evt', 'event'),
        (r'\$callback|\$handler|\$fn', 'callback function'),
    ]

    matched = []
    for pattern, context in param_patterns:
        if re.search(pattern, param_lower):
            matched.append(context)

    if matched:
        if len(matched) == 1:
            return f"Operates on {matched[0]}."
        else:
            return f"Operates on {', '.join(matched[:-1])} and {matched[-1]}."

    return ''


def _get_file_context(file_path: str) -> str:
    """Get domain context from the file path.

    Returns a brief context phrase or empty string.
    """
    normalized = file_path.replace('\\', '/')

    for path_prefix, context in FILE_PATH_CONTEXT.items():
        if path_prefix in normalized:
            return context

    return ''


def _humanize_class_name(class_name: str) -> str:
    """Convert a class name to a readable lowercase phrase.

    Examples:
        'DB'           -> 'database'
        'MySQL'        -> 'MySQL'
        'CellOperations' -> 'cell'
    """
    lower = class_name.lower()
    if lower in COMPOUND_WORDS:
        return COMPOUND_WORDS[lower]
    if lower == 'db':
        return 'database'
    # Strip common suffixes
    for suffix in ('Operations', 'Manager', 'Handler', 'Helper', 'Service', 'Factory'):
        if class_name.endswith(suffix) and len(class_name) > len(suffix):
            base = class_name[:-len(suffix)]
            parts = _split_name_parts(base)
            return _humanize_noun_parts(parts)
    parts = _split_name_parts(class_name)
    return _humanize_noun_parts(parts)


def _extract_first_param_name(params: str) -> str:
    """Extract a readable name from the first parameter.

    Examples:
        '$tableName, $where'  -> 'table name'
        'string $key'         -> 'key'
        'args'                -> 'args'
    """
    if not params:
        return ''
    # Get first param
    first = params.split(',')[0].strip()
    # Remove type hint
    parts = first.split()
    name = parts[-1] if parts else first
    # Remove $ prefix
    name = name.lstrip('$')
    if not name or len(name) < 2:
        return ''
    # Split and humanize
    name_parts = _split_name_parts(name)
    return _humanize_noun_parts(name_parts)


def _clean_awkward_phrasing(description: str) -> str:
    """Fix common awkward phrasings in generated descriptions.

    Fixes:
    - "and or" -> "and/or"
    - "getmysql..." -> "MySQL ..."
    - Double words from prefix stripping
    """
    # Fix "and or" -> "and/or"
    description = re.sub(r'\band or\b', 'and/or', description, flags=re.IGNORECASE)

    # Fix repeated words like "MySQL get MySQL set values" -> "MySQL get set values"
    # When a word appears twice due to prefix + camelCase containing the same word
    description = re.sub(
        r'(?i)\b(MySQL|SQL|HTML|CSS|PHP|HTTP|AJAX|JSON|XML)\b(.+?)\b\1\b',
        lambda m: m.group(1) + m.group(2),
        description
    )

    # Clean up double spaces
    description = re.sub(r'  +', ' ', description)

    # Fix concatenated lowercase runs that should be separated
    # e.g., "getmysqlsetvalues" -> detect and split
    description = re.sub(
        r'(?<=\s)([a-z]{3,})([a-z]{3,})(?=[\s.])',
        lambda m: _try_split_concatenated(m.group(0)),
        description
    )

    return description


def _try_split_concatenated(word: str) -> str:
    """Try to split a concatenated lowercase word into readable parts.

    Uses known compound words and common word boundaries.
    """
    lower = word.lower()
    # Check if it's a known compound
    if lower in COMPOUND_WORDS:
        return COMPOUND_WORDS[lower]

    # Try to find a split point using known prefixes
    known_prefixes = ['get', 'set', 'add', 'del', 'new', 'old', 'all', 'has', 'max', 'min']
    for prefix in known_prefixes:
        if lower.startswith(prefix) and len(lower) > len(prefix) + 2:
            rest = lower[len(prefix):]
            if rest in COMPOUND_WORDS:
                return f"{prefix} {COMPOUND_WORDS[rest]}"
            return f"{prefix} {rest}"

    return word


def describe_function(func: dict) -> str:
    """Generate a rich description for a single function.

    Priority order:
    1. Docblock summary (if available and useful)
    2. Inferred from function name (verb+noun analysis)
    3. Inferred from parameters
    4. Inferred from return type
    5. Inferred from file path context
    6. Minimal fallback

    Returns a 1-2 sentence description.
    """
    # Priority 1: Use existing docblock summary if it's useful
    summary = (func.get('summary') or '').strip()
    if summary and not summary.startswith('@') and len(summary) > 10:
        return summary

    # Extract from full doc if summary field was bad but docblock exists
    doc = (func.get('doc') or '').strip()
    if doc:
        extracted = _extract_meaningful_summary(doc)
        if extracted and not extracted.startswith('@') and len(extracted) > 10:
            return extracted

    # Priority 2: Infer from function name
    name = func.get('short_name', '')
    class_name = func.get('class_name') or ''
    verb, noun = _extract_verb_and_noun(name)
    description = ''

    if verb and verb in VERB_TEMPLATES:
        # Fix Issue 1: "the value" fallback for bare verb names (get, init, count)
        # Use class context if noun is the generic fallback
        if noun == 'the value' and class_name:
            noun = f"the {_humanize_class_name(class_name)} value"
        elif noun == 'the value' and func.get('params'):
            # Try to infer from first param name
            first_param = _extract_first_param_name(func['params'])
            if first_param:
                noun = first_param
        elif noun == 'the value':
            # Last resort: use file path context
            file_context = _get_file_context(func.get('file', ''))
            if file_context:
                noun = f"the {file_context} component"
        description = VERB_TEMPLATES[verb].format(noun=noun)
    else:
        # No recognized verb -- humanize name and add context
        parts = _split_name_parts(name)
        readable = _humanize_noun_parts(parts)
        # Check if it looks like a callback/handler (e.g., 'onClick', 'onSubmit')
        if name.startswith('on') and len(parts) >= 2:
            event = _humanize_noun_parts(parts[1:])
            description = f"Event handler for {event}."
        elif class_name:
            # Fix Issue 6: Add class context for bare method names
            description = f"{class_name} method for {readable}."
        elif len(readable) < 12:
            # Fix Issue 4: Very short names -- add file context inline
            file_context = _get_file_context(func.get('file', ''))
            if file_context:
                description = f"Handles {readable} for {file_context}."
            else:
                description = f"Handles {readable}."
        else:
            description = f"Handles {readable}."

    # Fix Issue 2: Clean up awkward phrasing
    description = _clean_awkward_phrasing(description)

    # Priority 3: Enrich with parameter context
    params = func.get('params', '')
    param_hint = _infer_from_params(params)
    if param_hint and param_hint not in description:
        description = f"{description} {param_hint}"

    # Priority 4: Add return type hint
    return_type = func.get('return_type', 'unknown')
    if return_type and return_type != 'unknown':
        # Clean up return type
        clean_type = return_type.strip('?').strip()
        type_hint = RETURN_TYPE_HINTS.get(clean_type, '')
        if type_hint and type_hint not in description:
            description = f"{description} {type_hint}"

    # Priority 5: Add file path context if description is thin
    if len(description) < 40:
        file_context = _get_file_context(func.get('file', ''))
        if file_context:
            description = f"{description} Part of {file_context}."

    return description.strip()


def _extract_meaningful_summary(doc: str) -> str:
    """Extract a meaningful summary from a docblock.

    Skips @tags, empty lines, and boilerplate. Returns the first
    substantial prose line.
    """
    for raw_line in doc.splitlines():
        line = raw_line.strip()
        # Strip docblock syntax
        line = re.sub(r'^/\*\*\s*', '', line)
        line = re.sub(r'\*/$', '', line)
        line = re.sub(r'^\*\s*', '', line).strip()

        # Skip empty, tags, and boilerplate
        if not line:
            continue
        if line.startswith('@'):
            continue
        if line in ('/**', '*/', '*'):
            continue
        if len(line) < 5:
            continue

        return line

    return ''


def describe_category(cat_name: str, functions: List[dict], taxonomy: dict = None) -> str:
    """Generate a rich description for a category.

    Reads descriptions from the project's taxonomy config when available.
    Falls back to generating a description from function analysis.

    The taxonomy parameter is a dict loaded from _taxonomy.json. When provided,
    its category descriptions take priority over generated descriptions.
    """
    # Strip part suffixes for lookup
    base_name = re.sub(r'-(part-\d+|[a-z](?:-[a-z])?)$', '', cat_name)

    # Try taxonomy first
    if taxonomy:
        desc = _get_taxonomy_description(base_name, taxonomy)
        if desc:
            return desc

    # Generate from function analysis
    return _generate_category_description(cat_name, functions)


def _get_taxonomy_description(cat_key: str, taxonomy: dict) -> str:
    """Look up a category description from taxonomy config.

    Supports both "top-category" and "top-category/subcategory" key formats.
    Returns empty string if no taxonomy entry exists.
    """
    categories = taxonomy.get("categories", {})

    # Try "top/sub" format
    if "/" in cat_key:
        top, sub = cat_key.split("/", 1)
        top_cat = categories.get(top, {})
        subcats = top_cat.get("subcategories", {})
        if sub in subcats:
            sub_entry = subcats[sub]
            if isinstance(sub_entry, dict):
                return sub_entry.get("description", "")
            return str(sub_entry)
        # Fall back to top-level
        if "description" in top_cat:
            return top_cat["description"]
        return ""

    # Try top-level match
    if cat_key in categories:
        cat_entry = categories[cat_key]
        if isinstance(cat_entry, dict):
            return cat_entry.get("description", "")
        return str(cat_entry)

    return ""


def _generate_category_description(cat_name: str, functions: List[dict]) -> str:
    """Generate a category description by analyzing contained functions.

    When no template exists, analyzes the functions to find common patterns
    and generates a meaningful description.
    """
    readable_name = cat_name.replace('-', ' ').replace('_', ' ')

    if not functions:
        return CATEGORY_DESCRIPTION_FALLBACK.format(
            name=cat_name, readable_name=readable_name
        )

    # Analyze common verbs in functions
    verb_counts: Dict[str, int] = defaultdict(int)
    file_contexts: Dict[str, int] = defaultdict(int)
    param_contexts: Dict[str, int] = defaultdict(int)

    for func in functions:
        verb, _ = _extract_verb_and_noun(func['short_name'])
        if verb:
            verb_counts[verb] += 1

        ctx = _get_file_context(func.get('file', ''))
        if ctx:
            file_contexts[ctx] += 1

    # Build description from analysis
    parts = []

    # What the functions do (top verbs)
    top_verbs = sorted(verb_counts.items(), key=lambda x: -x[1])[:3]
    if top_verbs:
        verb_phrases = []
        for v, _ in top_verbs:
            if v in ('get', 'set'):
                verb_phrases.append(f"{v}ting")
            elif v == 'is' or v == 'has':
                verb_phrases.append(f"checking ({v})")
            elif v.endswith('e'):
                verb_phrases.append(f"{v[:-1]}ing")  # create -> creating
            else:
                verb_phrases.append(f"{v}ing")
        actions = ', '.join(verb_phrases)
        parts.append(
            f"Functions primarily focused on {actions} "
            f"related to {readable_name}."
        )
    else:
        parts.append(
            f"Functions related to {readable_name}."
        )

    # Where they live (file context)
    if file_contexts:
        top_ctx = max(file_contexts, key=file_contexts.get)
        parts.append(f"Part of the {top_ctx} subsystem.")

    # Use case
    parts.append(
        f"Use these when working with {readable_name} features."
    )

    return ' '.join(parts)


# =============================================================================
# ENHANCED MARKDOWN GENERATION
# =============================================================================

def generate_enhanced_category_markdown(cat_name: str, funcs: List[dict]) -> str:
    """Generate enhanced markdown with rich descriptions for a category."""
    title = cat_name.replace('-', ' ').replace('_', ' ').title()
    description = describe_category(cat_name, funcs)

    lines = [
        f"# {title}",
        "",
        description,
        "",
        f"**Function count:** {len(funcs)}",
        "",
        "---",
        "",
    ]

    # Sort functions by name
    funcs_sorted = sorted(funcs, key=lambda f: f['short_name'].lower())

    for func in funcs_sorted:
        # Function header
        visibility = f"{func['visibility']} " if func.get('visibility') else ''
        static = 'static ' if func.get('is_static') else ''
        async_marker = 'async ' if func.get('is_async') else ''

        signature = f"{visibility}{static}{async_marker}{func['short_name']}({func['params']})"
        if func.get('return_type') and func['return_type'] != 'unknown':
            signature += f": {func['return_type']}"

        lines.append(f"## {func['short_name']}")
        lines.append("")

        # Rich description
        func_desc = describe_function(func)
        if func_desc:
            lines.append(func_desc)
            lines.append("")

        lines.append(f"**Signature:** `{signature}`")
        lines.append("")

        # Location
        location = f"{func['file']}:{func['line_start']}"
        if func['line_end'] != func['line_start']:
            location += f"-{func['line_end']}"
        lines.append(f"**Location:** `{location}`")
        lines.append("")

        # Namespace/Class
        if func.get('namespace'):
            lines.append(f"**Namespace:** `{func['namespace']}`")
            lines.append("")
        if func.get('class_name'):
            lines.append(f"**Class:** `{func['class_name']}`")
            lines.append("")

        # Attributes
        if func.get('attributes'):
            attrs = ', '.join(func['attributes'])
            lines.append(f"**Attributes:** `{attrs}`")
            lines.append("")

        lines.append("---")
        lines.append("")

    return '\n'.join(lines)


def generate_enhanced_index(
    categories: Dict[str, List[dict]], project_name: str
) -> str:
    """Generate enhanced project index with category descriptions."""
    total_funcs = sum(len(funcs) for funcs in categories.values())

    lines = [
        f"# {project_name} Function Map",
        "",
        f"**Total functions:** {total_funcs}",
        f"**Categories:** {len(categories)}",
        "",
        "## Categories",
        "",
    ]

    # Group categories by base name
    base_groups: Dict[str, List[Tuple[str, List[dict]]]] = defaultdict(list)
    for cat_name, funcs in categories.items():
        base = re.sub(r'-(part-\d+|[a-z](?:-[a-z])?)$', '', cat_name)
        base_groups[base].append((cat_name, funcs))

    for base, cats in sorted(base_groups.items()):
        total = sum(len(funcs) for _, funcs in cats)
        base_title = base.replace('-', ' ').replace('_', ' ').title()

        # Get description for the base category
        all_funcs = []
        for _, funcs in cats:
            all_funcs.extend(funcs)
        desc = describe_category(base, all_funcs)
        # Truncate for index listing
        short_desc = desc[:120] + '...' if len(desc) > 120 else desc

        if len(cats) == 1:
            cat_name, funcs = cats[0]
            lines.append(f"### [{base_title}]({cat_name}.md) ({len(funcs)} functions)")
            lines.append(f"  {short_desc}")
            lines.append("")
        else:
            lines.append(f"### {base_title} ({total} functions)")
            lines.append(f"  {short_desc}")
            lines.append("")
            for cat_name, funcs in sorted(cats):
                title = cat_name.replace('-', ' ').replace('_', ' ').title()
                lines.append(f"  - [{title}]({cat_name}.md) ({len(funcs)} functions)")
            lines.append("")

    lines.extend([
        "## Usage",
        "",
        "1. Browse categories above to find relevant functions",
        "2. Click category link to see function signatures, descriptions, and locations",
        "3. Use location info to read source code for implementation details",
        "",
    ])

    return '\n'.join(lines)


# =============================================================================
# MAIN: Apply descriptions to existing function map
# =============================================================================

def main():
    import argparse
    import sys

    ap = argparse.ArgumentParser(
        prog='describe',
        description='Universal description engine for function maps. '
                    'Use --stats or --dry-run to analyze description coverage. '
                    'For full categorization + markdown generation, use categorize.py instead.'
    )
    ap.add_argument(
        '--project', default='',
        help='Project name (default: most recent in ~/.claude/functionmap)'
    )
    ap.add_argument(
        '--dry-run', action='store_true',
        help='Preview descriptions without writing files'
    )
    ap.add_argument(
        '--stats', action='store_true',
        help='Show description coverage statistics'
    )
    args = ap.parse_args()

    base_dir = Path.home() / '.claude' / 'functionmap'

    # Find project
    if args.project:
        project_dir = base_dir / args.project
    else:
        meta_files = list(base_dir.glob('*/_meta.json'))
        if not meta_files:
            print("[describe] No projects found", file=sys.stderr)
            return 1
        meta_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        project_dir = meta_files[0].parent

    project_name = project_dir.name
    print(f"[describe] Project: {project_name}")

    # Load functions
    functions_json = project_dir / '_functions.json'
    if not functions_json.exists():
        print(f"[describe] ERROR: {functions_json} not found", file=sys.stderr)
        return 1

    with open(functions_json, 'r', encoding='utf-8') as f:
        functions = json.load(f)

    print(f"[describe] Functions: {len(functions)}")

    if args.stats:
        _print_stats(functions)
        return 0

    if args.dry_run:
        _preview_descriptions(functions)
        return 0

    # Default: show stats (full run is handled by categorize.py)
    print("[describe] Use --stats for coverage analysis or --dry-run for preview.")
    print("[describe] For full categorization + markdown generation, run categorize.py")
    _print_stats(functions)
    return 0


def _print_stats(functions: List[dict]) -> None:
    """Print description coverage statistics."""
    total = len(functions)
    has_doc = sum(1 for f in functions if (f.get('doc') or '').strip())
    has_summary = sum(
        1 for f in functions
        if (f.get('summary') or '').strip()
        and not f['summary'].startswith('@')
    )

    # Test inference coverage
    has_verb = 0
    for f in functions:
        verb, _ = _extract_verb_and_noun(f['short_name'])
        if verb and verb in VERB_TEMPLATES:
            has_verb += 1

    inferred = 0
    for f in functions:
        desc = describe_function(f)
        if desc and 'operations' not in desc:  # "operations" = weak fallback
            inferred += 1

    print(f"\n=== Description Coverage ===")
    print(f"  Total functions:     {total}")
    print(f"  Has docblock:        {has_doc} ({has_doc*100//total}%)")
    print(f"  Has useful summary:  {has_summary} ({has_summary*100//total}%)")
    print(f"  Verb-inferable:      {has_verb} ({has_verb*100//total}%)")
    print(f"  Total describable:   {inferred} ({inferred*100//total}%)")
    print(f"  Needs fallback:      {total - inferred} ({(total-inferred)*100//total}%)")


def _preview_descriptions(functions: List[dict]) -> None:
    """Preview generated descriptions for a sample of functions."""
    # Show a mix: some with docs, some without
    samples = []

    # Pick 5 with docs
    with_docs = [f for f in functions if (f.get('doc') or '').strip()][:5]
    samples.extend(with_docs)

    # Pick 10 without docs but with recognizable verbs
    without_docs = [
        f for f in functions
        if not (f.get('doc') or '').strip()
        and _extract_verb_and_noun(f['short_name'])[0] in VERB_TEMPLATES
    ][:10]
    samples.extend(without_docs)

    # Pick 5 without docs and no verb match (hardest case)
    hard_cases = [
        f for f in functions
        if not (f.get('doc') or '').strip()
        and _extract_verb_and_noun(f['short_name'])[0] not in VERB_TEMPLATES
    ][:5]
    samples.extend(hard_cases)

    print(f"\n=== Description Preview ({len(samples)} samples) ===\n")
    for func in samples:
        name = func['short_name']
        has_doc = bool((func.get('doc') or '').strip())
        source = 'DOCBLOCK' if has_doc else 'INFERRED'
        desc = describe_function(func)
        print(f"  [{source}] {name}")
        print(f"    -> {desc}")
        print()


if __name__ == '__main__':
    raise SystemExit(main())
